services:
  # SERVICIO 1: BASE DE DATOS
  mysqldb:
    image: mysql:8.0
    container_name: mi_mysql_docker
    # Mantenemos el comando de compatibilidad que agregamos antes
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: bdd_formulario
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./bdd:/docker-entrypoint-initdb.d 
    # NUEVO: Verificación de salud. Docker preguntará cada 5s si MySQL ya responde.
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always

  # SERVICIO 2: APP SPRING BOOT 
  app:
    build: .
    container_name: mi_backend
    ports:
      - "8085:8085"
    depends_on:
      mysqldb:
        # NUEVO: Esperar a que el healthcheck de arriba de OK antes de iniciar
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/bdd_formulario?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always

  # SERVICIO 3: UI PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mi_phpmyadmin
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: always

volumes:
  db_data: