services:
  # SERVICIO 1: BASE DE DATOS
  mysqldb:
    image: mysql:8.0
    container_name: mi_mysql_docker
    environment:
      MYSQL_DATABASE: bdd_formulario
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" # acceso externo por el puerto 3307
    volumes:
      - db_data:/var/lib/mysql
      # si la base de datos no existe, se crea a partir del script SQL
      - ./bdd:/docker-entrypoint-initdb.d 
    restart: always

  #SERVICIO 2: APP SPRING BOOT 
  app:
    build: .
    container_name: mi_backend
    ports:
      - "8085:8085" # la  aplicación web
    depends_on:
      - mysqldb
    environment:
      # conexión interna usando el nombre del servicio 'mysqldb'
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/bdd_formulario?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always

  # SERVICIO 3: UI PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mi_phpmyadmin
    environment:
      PMA_HOST: mysqldb      # se conecta al servicio de BD de arriba
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"            # accederemos por el puerto 8081
    depends_on:
      - mysqldb
    restart: always

volumes:
  db_data: